### PR TITLE
Fix running buffet without options

### PR DESCRIPTION
**Pull request by mirasrael**
It fails to extract options from empty command line arguments to run specs in spec folder by default

### CODE REVIEW

**Comment by ghost** [comment]
Thanks very much for the pull request. I'll make some comments on the individual commits.

**Comment by mirasrael** [comment]
First of all, actually I want only suggest as pull request first commit (as it described in subject) =) But github automaticly attach all following commits to this pull request. I'm still float in this workflow. All other commits just working copy of my experiments to get things working. Easiest way for me to deliver changes to remote machines - its by github link in Gemfile.
But, sure, I can comment my commits and may be they will become part of gem. Why not? :)

**Comment by ghost** [comment]
Yeah, sounds like a good idea!

**Comment by mirasrael** [comment]
I think I can make tomorrow some rework of my code and change commit messages to make them more clear.

**Comment by mirasrael** [comment]
I have done some refactoring

**Comment by lann** [comment]
@mirasrael in the pull request dialog you can click the "Change Commits" button to specify a specific commit instead of a branch. I'm not sure if you can edit the source of an existing pull request though.

**Pull request closed without merging**
